### ISSUE TITLE
Kalendern visar rätt antal event. Men visar inte olika event. 

### ISSUE THREAD

**Issue by johanrovala** [OttoBergman/Timeedit-app-android#1]
Om vi för tillfället lägger till t.ex. 1bd105 så ser vi i kalendervyn att rätt datum har rätt antal events. Däremot står eventen listade som samma sak. 

Exempel: 25/6 - Självstudier och föreläsning. Olika tider
Kalendern visar Föreläsning två gånger med samma tid. Alltså samma event.

**Comment by OttoBergman** [comment]
Popup visar nu rätt information! :)
